version: '3.8'

services:
  backend:
    build: ./Backend
    container_name: backend-assets
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_NAME=asset_management
      - DB_PORT=5432

  employee-assets:
    build: ./Employee-Assets
    container_name: employee-assets
    ports:
      - "8030:80"
    depends_on:
      - backend

  hr-assets:
    build: ./HR-Assets
    container_name: hr-assets
    ports:
      - "8032:80"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    container_name: postgres-assets
    ports:
      - "5002:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: asset_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:

